### ISSUE TITLE
[BUG] Mole Dig Counts as Kill

### ISSUE THREAD

**Issue by BuzzfeedBlue** [ChunkyAtlas/monster-monitor#1]
Every time the giant mole digs it counts in the plugin as a kill

**Comment by ChunkyAtlas** [comment]
Ahhh interesting, I think I may know why, I'll push a fix tonight

**Comment by BuzzfeedBlue** [comment]
Appreciate the fast reply. Plugin seems really useful otherwise. While I have your attention I would love to just have an infobox that shows total kill count for a specified monster / boss that updates as soon as you kill it and no plugins currently have that feature. If you are willing to look into implementing that I would be very grateful

**Comment by ChunkyAtlas** [comment]
> Appreciate the fast reply. Plugin seems really useful otherwise. While I have your attention I would love to just have an infobox that shows total kill count for a specified monster / boss that updates as soon as you kill it and no plugins currently have that feature. If you are willing to look into implementing that I would be very grateful

The panel displays that info for you! but I'm assuming that you want something that would be on screen? similar to the kill limit?

**Comment by BuzzfeedBlue** [comment]
Yes I know the side panel displays the info which is why I looked into the plugin in the first place! But yeah, I would love a little draggable infobox that just had total kills and an icon or name of the boss over the game area

**Comment by ChunkyAtlas** [comment]
> Yes I know the side panel displays the info which is why I looked into the plugin in the first place! But yeah, I would love a little draggable infobox that just had total kills and an icon or name of the boss over the game area

I'll tinker with the idea and make it an option overlay you can use per NPC, but it may not be pushed out immediately. Currently working on a few other bug fixes and some additional features :)

**Comment by BuzzfeedBlue** [comment]
Of course, thanks again. I appreciate all the work done for the plugin

**Comment by ChunkyAtlas** [comment]
> Of course, thanks again. I appreciate all the work done for the plugin

I believe I have fixed the problem, but I was working on some other stuff and new features with the plugin and haven’t pushed the fix as of yet, I’m shooting for either tonight or tomorrow to submit the update to the Plugin Hub team. Just wanted to share an update with ya!

**Comment by ChunkyAtlas** [comment]
This  issue has been resolved with the update today!
